version: !!str 3

services:
  rancher:
    image: rancher/rancher:latest
    container_name: rancher
    volumes:
      - rancher-vol:/var/lib/rancher
    restart: unless-stopped
    ports:
      - '543:443'
      - '144:80'
    networks:
      - cicd
    labels:
      - "app.dws.name=rancher"

  flame:
    image: pawelmalak/flame
    container_name: poseidon
    volumes:
      - /mnt/c/Users/mike/portainer/flame:/app/data
    ports:
      - 5005:5005
    environment:
      - PASSWORD=poseidon
    restart: unless-stopped
    networks:
      - cicd
    labels:
      - "app.dws.name=flame"

  jenkins:
    image: ssbostan/jenkins:lts-slim
    container_name: jenkins
    restart: unless-stopped
    environment:
      - "DOCKER_HOST=tcp://docker:2376"
      - "DOCKER_TLS_VERIFY=1"
      - "M2_HOME=/opt/apache-maven-3.8.4"
    volumes:
      - "jenkins_data:/var/jenkins_home"
      - "docker_certs_client:/var/jenkins_home/.docker"
    networks:
      - cicd
    ports:
      - "8090:8080"
      - "50000:50000"
    labels:
      - "app.dws.name=jenkins"

  docker:
    image: docker:dind
    container_name: docker
    restart: unless-stopped
    privileged: true
    command: ["--insecure-registry", "REGISTRY:4444"]
    volumes:
      - "docker_data:/var/lib/docker"
      - "docker_certs:/certs"
      - "docker_certs_client:/certs/client"
      - "jenkins_data:/var/jenkins_home"
    networks:
      - cicd
    expose:
      - "2376"
    labels:
      - "app.dws.name=docker"

  gitea:
    image: gitea/gitea:1.14
    container_name: gitea
    restart: unless-stopped
    volumes:
      - "gitea_data:/data"
    networks:
      - cicd
    ports:
      - "3000:3000"
      - "2222:22"
    labels:
      - "app.dws.name=gitea"

  sonarqube:
    image: sonarqube:7.6-community
    container_name: sonarqube
    restart: unless-stopped
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    networks:
      - cicd
    ports:
      - '9001:9000'
    environment:
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
      - sonar.jdbc.url=jdbc:postgresql://postgres:5432/sonar
    labels:
      - "app.dws.name=sonarqube"

  postgres:
    image: postgres
    container_name: postgres
    networks:
      - cicd
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    labels:
      - "app.dws.name=postgres"

  mysql:
    image: mysql:5.7
    container_name: mysql
    networks:
      - cicd
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - mysql:/var/lib/mysql
    labels:
      - "app.dws.name=mysql"

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    environment:
        ADMINER_DESIGN: dracula
    networks:
      - cicd
    ports:
      - '8084:8080'

networks:
  cicd:
    driver: bridge

volumes:
  jenkins_data:
  registry_data:
  docker_data:
  docker_certs:
  docker_certs_client:
  gitea_data:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  postgresql:
  postgresql_data:
  mysql:
  rancher-vol:
