apiVersion: v1
kind: Secret
metadata:
  name: aline-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  APP_USER_ACCESS_KEY: {{ .Values.appUserAccessKey }}
  APP_USER_SECRET_KEY: {{ .Values.appUserSecretKey }}
  ENCRYPT_SECRET_KEY: {{ .Values.encryptSecretKey }}
  JWT_SECRET_KEY: {{ .Values.jwtSecretKey }}
  MYSQL_ROOT_PASSWORD: {{ .Values.rootPassword }}
