apiVersion: v1
kind: ConfigMap
metadata:
  name: aline-configmap
  namespace: {{ .Values.namespace }}
data:
  ADMINER_DEFAULT_SERVER: "mysql-db"
  ADMINER_DESIGN: {{ .Values.adminerDesign }}
  MYSQL_ROOT_PASSWORD: {{ .Values.rootPassword }}
  MYSQL_DATABASE: "alinedb"
  DDL_AUTO: "create-only"
  DB_USERNAME: "root"
  DB_PASSWORD: {{ .Values.rootPassword }}
  DB_HOST: "mysql-db"
  DB_PORT: "3306"
  DB_NAME: "alinedb"
  S3_TEMPLATE_BUCKET: {{ .Values.s3TemplateBucket }}
  PORTAL_ADMIN: "fe-admin:3000"
  PORTAL_DASHBOARD: "fe-dashboard:4200"
  PORTAL_LANDING: "fe-landing:3000"

