apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-env
  namespace: jenkins-stack
  labels:
    app.kubernetes.io/name: registry
data:
  REGISTRY_FIELDS_ENVIRONMENT: production
  REGISTRY_HTTP_ADDR: 0.0.0.0:443
  REGISTRY_HTTP_TLS_CERTIFICATE: /certs/registry.crt
  REGISTRY_HTTP_TLS_KEY: /certs/registry.key
