apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-data
  namespace: jenkins-stack
  labels:
    app.kubernetes.io/name: registry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
