apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: jenkins-stack
  labels:
    app.kubernetes.io/name: registry
spec:
  type: LoadBalancer
  ports:
    - port: 443
      protocol: TCP
  selector:
    app.kubernetes.io/name: registry
