apiVersion: v1
kind: Service
metadata:
  name: docker
  namespace: jenkins-stack
  labels:
    app.kubernetes.io/name: docker
spec:
  type: ClusterIP
  ports:
    - port: 2376
      protocol: TCP
  selector:
    app.kubernetes.io/name: docker

