apiVersion: apps/v1
kind: Deployment
metadata:
  name: poseidon
  namespace: jenkins-stack
  labels:
    app.kubernetes.io/name: poseidon
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: poseidon
  template:
    metadata:
      labels:
        app.kubernetes.io/name: poseidon
    spec:
      containers:
        - name: poseidon
          image: gitea/gitea:1.14
          env:
            - name: TZ
              value: UTC0
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 2
              memory: 2Gi
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: poseidon-data
