apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: poseidon-data
  namespace: jenkins-stack
  labels:
    app.kubernetes.io/name: poseidon
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
