apiVersion: v1
kind: Service
metadata:
  name: gitea
  namespace: jenkins-stack
  labels:
    app.kubernetes.io/name: gitea
spec:
  type: LoadBalancer
  ports:
    - name: ssh
      port: 22
    - name: http
      targetPort: 3000
      port: 80
  selector:
    app.kubernetes.io/name: gitea
